version = "0.8.1"
author = "Jaremy Creechley"
description = "A slot and signals implementation for the Nim programming language"
license = "MIT"
srcDir = "."

requires "nim >= 2.0.12 & < 2.2.0"
requires "variant >= 0.2.12"
requires "threading#master"
requires "patty >= 0.3.4"
