version = "0.11.5"
author = "Jaremy Creechley"
description = "A slot and signals implementation for the Nim programming language"
license = "MIT"
srcDir = "."

requires "nim >= 2.0.2"
requires "variant >= 0.2.12"
requires "threading >= 0.2.1"
requires "stack_strings"
requires "patty >= 0.3.4"
