on:
  pull_request:
    branches:
    - "*"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.0.14'
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-${{ hashFiles('sigils.nimble') }}

    - name: Install Nimble
      run: |
        # nimble install nimble@\#master
        nim -v
        nimble -v

    - name: Install Deps
      run: |
        # new atlas workspace
        nimble install --useSystemNim -d --verbose

    - name: Build Tests
      run: |
        nimble --useSystemNim test
